// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ScrollToInSolutionExplorer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidScrollToInSolutionExplorerPackageString = "ba7408f0-ed7d-4efa-85ef-2d648b9a3274";
        public static Guid guidScrollToInSolutionExplorerPackage = new Guid(guidScrollToInSolutionExplorerPackageString);

        public const string guidScrollToInSolutionExplorerPackageCmdSetString = "d41f8793-ad72-4ed1-af0f-cec3de2b9a61";
        public static Guid guidScrollToInSolutionExplorerPackageCmdSet = new Guid(guidScrollToInSolutionExplorerPackageCmdSetString);

        public const string guidImagesString = "3ef7db1b-bdbc-4232-9d89-9f8a8503e7e3";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ScrollToInSolutionExplorerMenuGroup = 0x1020;
        public const int ScrollToInSolutionExplorerCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}